// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC427QhtHOgF949ACpcor1i_4p-212h7Pg',
    appId: '1:227367221532:web:b1562e1e4023473b8d62d9',
    messagingSenderId: '227367221532',
    projectId: 'practice-54277',
    authDomain: 'practice-54277.firebaseapp.com',
    storageBucket: 'practice-54277.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ_QwCyakXoqsjGpSCPw4CsY0i2xyVw2w',
    appId: '1:227367221532:android:2202e3634f76757d8d62d9',
    messagingSenderId: '227367221532',
    projectId: 'practice-54277',
    storageBucket: 'practice-54277.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARms7MLDiXDHiFlh6ulPHFh-jqC_nwuLQ',
    appId: '1:227367221532:ios:e6a4b1e4c41dded08d62d9',
    messagingSenderId: '227367221532',
    projectId: 'practice-54277',
    storageBucket: 'practice-54277.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARms7MLDiXDHiFlh6ulPHFh-jqC_nwuLQ',
    appId: '1:227367221532:ios:e6a4b1e4c41dded08d62d9',
    messagingSenderId: '227367221532',
    projectId: 'practice-54277',
    storageBucket: 'practice-54277.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC427QhtHOgF949ACpcor1i_4p-212h7Pg',
    appId: '1:227367221532:web:f2ed2fd9ce71ab048d62d9',
    messagingSenderId: '227367221532',
    projectId: 'practice-54277',
    authDomain: 'practice-54277.firebaseapp.com',
    storageBucket: 'practice-54277.appspot.com',
  );
}
